apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: poi-ingress
  namespace: api-dev
spec:
  ingressClassName: nginx
  rules:
    - host: "www"
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: poi-service
                port:
                  number: 80
            path: /api/poi
