apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: api-dev
spec:
  ingressClassName: nginx
  rules: 
    - http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: poi-service
                port:
                  number: 80
            path: /api/poi/
          - pathType: Prefix
            backend:
              service:
                name: trips-api-service
                port:
                  number: 80
            path: /api/trips/
          - pathType: Prefix
            backend:
              service:
                name: user-java-service
                port:
                  number: 80
            path: /api/user-java/
          - pathType: Prefix
            backend:
              service:
                name: userprofile-service
                port:
                  number: 80
            path: /api/user/

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  namespace: web-dev
spec:
  ingressClassName: nginx
  rules: 
    - http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: trip-viewer-service
                port:
                  number: 80
            path: /
