apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  labels:
    app: poi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: app-poi
        image: registrymjd9148.azurecr.io/tripinsights/poi:1.0
        ports:
        - containerPort: 80
        env:
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sql-secret
                key: password
                optional: false # same as default; "mysecret" must exist
                                # and include a key named "password
          - name: SQL_SERVER
            value: "sqlservermjd9148.database.windows.net"
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: sql-secret
                key: login
                optional: false # same as default; "mysecret" must exist
                                # and include a key named "password        
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"


apiVersion: v1
kind: Service
metadata:
  name: poi-service
spec:
  selector:
    app: poi
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

