apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: api-dev
  labels:
    app: poi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: app-poi
        image: registrymjd9148.azurecr.io/tripinsights/poi:1.0
        ports:
        - containerPort: 80
        env:
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sql-secret
                key: password
          - name: SQL_SERVER
            value: "sqlservermjd9148.database.windows.net"
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: sql-secret
                key: login
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"

---
apiVersion: v1
kind: Service
metadata:
  namespace: api-dev
  name: poi-service
spec:
  selector:
    app: poi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

