kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-access-rw
  namespace: api-dev
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["*"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-access-rw
  namespace: web-dev
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["*"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-access
  namespace: api-dev
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-access
  namespace: web-dev
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
