# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
  namespace: api-dev
spec:
  provider: azure
  secretObjects:
  - secretName: sql-secret
    data:
    - key: login
      objectName: sql-login
    - key: password
      objectName: sql-password
    type: Opaque      
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: 5f498c32-bd69-4d98-9436-12a3c69f60f3   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: aks-keyvault-team07        # Set to the name of your key vault
    #cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: sql-login
          objectType: secret              # object types: secret, key, or cert
          #objectVersion: "36940d8478b04bfb8c6ce1d0addff181"               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: sql-password
          objectType: secret
          #objectVersion: "f8e900605b2c41589a9f7ed001aff58f"
    tenantId: 21e795e9-eb25-4640-80ee-4e093c7a051b                 # The tenant ID of the key vault