apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips-api
  labels:
    app: trips-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trips-api
  template:
    metadata:
      labels:
        app: trips-api
    spec:
      containers:
      - name: app-trips-api
        image: registrymjd9148.azurecr.io/tripinsights/trips:1.0
        ports:
        - containerPort: 80
        env:
          - name: SQL_PASSWORD
            value: "yourStrong()Password"
          - name: SQL_SERVER
            value: "sqlserver"
          - name: OPENAPI_DOCS_URI
            value: "http://$EXTERNAL_IP"


apiVersion: v1
kind: Service
metadata:
  name: trips-api-service
spec:
  selector:
    app.kubernetes.io/name: trips-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

