apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  labels:
    app: userProfile
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: app-poi
        image: registrymjd9148.azurecr.io/tripinsights/userprofile:1.0
        ports:
        - containerPort: 80
        env:
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sql-secret
                key: password
          - name: SQL_SERVER
            value: "sqlservermjd9148.database.windows.net"
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: sql-secret
                key: login
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile-service
spec:
  selector:
     app: userprofile
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

